version: '3.9'
services:
  db:
    image: postgres:16
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: tool_keeper_ai_db
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
  
  api:
    build:
      context: ./back
      dockerfile: Dockerfile
    depends_on:
      - db
      - ml
    environment:
      - ConnectionStrings__DefaultConnection=Host=db;Port=5432;Database=tool_keeper_ai_db;Username=postgres;Password=postgres
      - ASPNETCORE_URLS=http://+:8001
    ports:
      - "8001:8001"

  ml:
    build:
      context: ./ml
      dockerfile: Dockerfile
    ports:
      - "8000:8000"

  front:
    build:
      context: ./front
      dockerfile: Dockerfile
    ports:
      - "80:80"

volumes:
  pgdata: